import { Destination, Trip, Bus } from '../types';

export const busTypes: Bus[] = [
  { id: '1', type: 'Scania', capacity: 50, amenities: ['AC', 'WiFi', 'TV', 'Charging Point'] },
  { id: '2', type: 'Yutong', capacity: 45, amenities: ['AC', 'TV', 'Charging Point'] },
  { id: '3', type: 'MAN', capacity: 52, amenities: ['AC', 'WiFi', 'TV', 'Charging Point', 'Snacks'] },
  { id: '4', type: 'Zhongtong', capacity: 48, amenities: ['AC', 'WiFi'] },
  { id: '5', type: 'Isuzu', capacity: 40, amenities: ['AC', 'TV'] },
];

export const destinations: Destination[] = [
  { id: '1', name: 'Nairobi Central', city: 'Nairobi', busStop: 'Nairobi Railway Station' },
  { id: '2', name: 'Mombasa CBD', city: 'Mombasa', busStop: 'Mombasa Bus Terminal' },
  { id: '3', name: 'Kisumu City', city: 'Kisumu', busStop: 'Kisumu Main Stage' },
  { id: '4', name: 'Nakuru Town', city: 'Nakuru', busStop: 'Nakuru Bus Park' },
  { id: '5', name: 'Eldoret City', city: 'Eldoret', busStop: 'Eldoret Main Terminal' },
  { id: '6', name: 'Thika Town', city: 'Thika', busStop: 'Thika Bus Station' },
  { id: '7', name: 'Naivasha', city: 'Naivasha', busStop: 'Naivasha Stage' },
];

export const trips: Trip[] = [
  {
    id: '1',
    origin: destinations[0],
    destination: destinations[1],
    departureTime: '06:00 AM',
    arrivalTime: '12:00 PM',
    duration: '6 hours',
    bus: busTypes[0],
    price: 1200,
    availableSeats: 25,
    date: '2024-01-20',
  },
  {
    id: '2',
    origin: destinations[0],
    destination: destinations[1],
    departureTime: '08:00 AM',
    arrivalTime: '02:00 PM',
    duration: '6 hours',
    bus: busTypes[1],
    price: 1000,
    availableSeats: 15,
    date: '2024-01-20',
  },
  {
    id: '3',
    origin: destinations[0],
    destination: destinations[2],
    departureTime: '07:30 AM',
    arrivalTime: '01:30 PM',
    duration: '6 hours',
    bus: busTypes[2],
    price: 1100,
    availableSeats: 30,
    date: '2024-01-20',
  },
  {
    id: '4',
    origin: destinations[0],
    destination: destinations[2],
    departureTime: '10:00 AM',
    arrivalTime: '04:00 PM',
    duration: '6 hours',
    bus: busTypes[3],
    price: 950,
    availableSeats: 20,
    date: '2024-01-20',
  },
  {
    id: '5',
    origin: destinations[0],
    destination: destinations[3],
    departureTime: '09:00 AM',
    arrivalTime: '12:30 PM',
    duration: '3.5 hours',
    bus: busTypes[4],
    price: 500,
    availableSeats: 35,
    date: '2024-01-20',
  },
  {
    id: '6',
    origin: destinations[0],
    destination: destinations[3],
    departureTime: '02:00 PM',
    arrivalTime: '05:30 PM',
    duration: '3.5 hours',
    bus: busTypes[0],
    price: 550,
    availableSeats: 28,
    date: '2024-01-20',
  },
  {
    id: '7',
    origin: destinations[0],
    destination: destinations[4],
    departureTime: '08:30 AM',
    arrivalTime: '03:00 PM',
    duration: '6.5 hours',
    bus: busTypes[1],
    price: 1150,
    availableSeats: 22,
    date: '2024-01-20',
  },
  {
    id: '8',
    origin: destinations[0],
    destination: destinations[5],
    departureTime: '07:00 AM',
    arrivalTime: '08:30 AM',
    duration: '1.5 hours',
    bus: busTypes[2],
    price: 250,
    availableSeats: 40,
    date: '2024-01-20',
  },
  {
    id: '9',
    origin: destinations[0],
    destination: destinations[6],
    departureTime: '09:30 AM',
    arrivalTime: '11:30 AM',
    duration: '2 hours',
    bus: busTypes[3],
    price: 300,
    availableSeats: 38,
    date: '2024-01-20',
  },
];